### ISSUE TITLE
Colors don't match with Unity Gradients (linear vs srgb)

### ISSUE THREAD

**Issue by fleity** [mitay-walle/com.mitay-walle.gradient-texture#22]
First off, great assets, love it, this makes life so much easier <3

I noticed something strange, I had a shader in which I used the SampleGradient node which I wanted to replace therefore I saved the gradient as preset, installed your package, created a gradient from that preset gradient and replaced the gradient in the shader with a texture sample. But the colors are not identical, quite different actually. 

The colors if I do a pow(x, 1/2.2) on the generated gradient therefore I think the gradient is not saved / created in linear colorspace? 
When encoded to png the texture has the srgb toggle but that is already to late, there should be one on the gradient asset?

![image](https://user-images.githubusercontent.com/7192666/205877607-89251bb5-66f7-4629-bc09-9d75511bd4c3.png)

**Comment by mitay-walle** [comment]
done, behaviour imitates TextureImporter.sRGB flag, after export to PNG flag is applied to TextureImporter. Exported PNG gamma and linear added to Samples.
1. if project color space is gamma - colors stay same
2.  If project color spaice is linearr - colors would same as gradient of sRGB is on, and Gradient.Evaluate().linear is used if sRGB is off.

![gradientTexture_srgb_inspector_preview](https://user-images.githubusercontent.com/5578552/206382785-14861413-ca4b-4355-9f4f-56cec8edb355.png)

**Comment by fleity** [comment]
fantastic, especially that the default is picked by project settings, very nice. 

I do get an error on package import due to a missing meta file though: 
`Asset Packages/com.mitay-walle.gradient-texture/Documentation/gradientTexture_srgb_inspector_preview.png has no meta file, but it's in an immutable folder. The asset will be ignored.`

(in fact I do get a few more errors but I believe those are better suited for a separate issue)
